#!/usr/bin/env bash
# Configures an Ubuntu server with Nginx and custom settings

# Install nginx
apt-get update -y && apt-get install -y nginx

# Get the hostname
HOST_NAME=$(hostname)

# Modify Nginx config to add X-Served-By header
CONFIG_FILE="/etc/nginx/sites-available/default"
if ! grep -q "X-Served-By" "$CONFIG_FILE"; then
    sed -i '/server_name _;/a \    add_header X-Served-By '"$HOST_NAME"';' "$CONFIG_FILE"
fi

# Create a simple index.html
echo "Hello World!" > /var/www/html/index.html

# Configure a redirect
if ! grep -q "location /redirect_me" "$CONFIG_FILE"; then
    echo -e "\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=bctljPSnV6s&t=350s;\n\t}" >> "$CONFIG_FILE"
fi

# Configure a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
if ! grep -q "error_page 404" "$CONFIG_FILE"; then
    echo -e "\n\terror_page 404 /custom_404.html;" >> "$CONFIG_FILE"
fi

# Validate and restart Nginx
nginx -t && service nginx restart
