#!/usr/bin/env bash
# First HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file rra
echo '
frontend collinsomwoyo.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 647502-web-01 54.87.210.141
        server 647502-web-02 54.163.177.34
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
