#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely; responds to SIGTERM with "I am invincible!!!"
trap 'echo "I am invincible!!!"' SIGTERM  # trap SIGTERM to display message
while true; do
echo "To infinity and beyond"
sleep 2
done
