#!/usr/bin/env bash
# Script to configure localhost and facebook.com IP mappings in /etc/hosts

# Copy /etc/hosts to a temporary file
cp /etc/hosts ~/hosts.new

# Add or modify the necessary entries
sed -i '/localhost/d' ~/hosts.new
echo "127.0.0.2 localhost" >> ~/hosts.new

sed -i '/facebook.com/d' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

# Replace the original /etc/hosts with the modified file
sudo cp -f ~/hosts.new /etc/hosts

# Clean up the temporary file
rm ~/hosts.new
